info:
  app:
    name: ${spring.application.name}
    version: ${APP_VERSION:unknown}
    environment: ${ENVIRONMENT:local}
    description: "Erweitertes Info-Profil f√ºr Actuator"
  build:
    time: ${BUILD_TIME:unknown}
    commit: ${GIT_COMMIT:unknown}
  kubernetes:
    pod-name: ${POD_NAME:unknown}
    namespace: ${POD_NAMESPACE:unknown}
    node: ${NODE_NAME:unknown}
    pod-ip: ${POD_IP:unknown}

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info
